version: '3.8'

services:
  mysql:
    build: .
    container_name: mysql_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: animais
    volumes:
      - ./data:/var/lib/mysql-files
